version: "3.9"

services:
  api:
    build: 
      context: .
      dockerfile: ./Docker/python/Dockerfile
    volumes:
      - ./hacku_backend:/usr/src/app
    ports:
      - 8000:8000
    command: ["python", "main.py"]
    restart: always

  postgres:
    image: postgres:14.0
    environment:
      POSTGRES_USER: yowayowa
      POSTGRES_PASSWORD: "pass" # あとでsecretsに変更する
      POSTGRES_DB: "pg"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    container_name: postgres-db
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
      - ./postgresql/init:/docker-entrypoint-initdb.d
